<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { adminApi } from '@/api/admin'
const rows=ref<any[]>([]); const cfg=ref<any>({}); const status=ref(''); const failure=ref<any>({})
async function load(){ rows.value = await adminApi.tasks(status.value); cfg.value = await adminApi.schedulerConfig(); failure.value = await adminApi.failureStats().catch(()=>({})) }
onMounted(load)
</script>
<template>
  <section class="task-page fade-slide"><div class="glass panel"><div class="head"><h2 class="gradient-title">解析任务管理</h2><div><el-select v-model="status" clearable placeholder="状态筛选" @change="load"><el-option label="queued" value="queued"/><el-option label="running" value="running"/><el-option label="failed" value="failed"/><el-option label="completed" value="completed"/></el-select><el-button class="is-glow" @click="load">刷新</el-button></div></div><el-table :data="rows" height="420"><el-table-column prop="id" label="ID" width="70"/><el-table-column prop="paper_id" label="文献"/><el-table-column prop="user_id" label="用户"/><el-table-column prop="task_type" label="任务类型"/><el-table-column prop="status" label="状态"/><el-table-column prop="priority" label="优先级"><template #default="{row}"><el-input-number v-model="row.priority" size="small" :min="0" :max="9" @change="adminApi.setTaskPriority(row.id,row.priority)" /></template></el-table-column><el-table-column prop="retry_count" label="重试"/><el-table-column prop="error_log" label="错误日志"/><el-table-column label="操作" width="150"><template #default="{row}"><el-button size="small" @click="adminApi.cancelTask(row.id).then(load)">终止</el-button><el-button size="small" @click="adminApi.retryTask(row.id).then(load)">重试</el-button></template></el-table-column></el-table></div><div class="glass panel"><h3>调度策略</h3><el-form label-position="top"><el-form-item label="最大并发任务数"><el-input-number v-model="cfg.max_concurrent_tasks" /></el-form-item><el-form-item label="单用户并发限制"><el-input-number v-model="cfg.per_user_concurrent" /></el-form-item><el-form-item label="超时秒数"><el-input-number v-model="cfg.timeout_seconds" /></el-form-item><el-button type="primary" @click="adminApi.saveSchedulerConfig(cfg)">保存配置</el-button></el-form><el-divider /> <h3>失败原因分类</h3><p>失败总数：{{ failure.failed_total || 0 }}</p><el-tag v-for="r in failure.by_reason" :key="r.reason">{{ r.reason }}：{{ r.count }}</el-tag></div></section>
</template>
<style scoped>.task-page{display:grid;grid-template-columns:1fr 360px;gap:18px}.panel{border-radius:28px;padding:22px}.head{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px}h2{margin:0;font-size:30px}.el-tag{margin:3px;white-space:normal;height:auto}</style>
